runtime: python38


handlers:
  - url: /static
    static_dir: static

  - url: /favicon.ico
    static_files: static/assets/img/favicon.ico
    upload: static/assets/img/favicon.ico

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
